### ISSUE TITLE
Crash when file not found

### ISSUE THREAD

**Issue by juliu-s** [maartenq/dnszonetest#29]
When specifying a file that does not exists, the applications crashes:

``[me@server]$ dnszonetest -d my.dns.server.pizza -rtns zone.pizza zone.pizza 
INFO      NAME SERVER: my.dns.server.pizza
INFO      NAME SERVER IP: 123.45.678.90
Traceback (most recent call last):
  File "/usr/bin/dnszonetest", line 9, in <module>
    load_entry_point('dnszonetest==1.0.5', 'console_scripts', 'dnszonetest')()
  File "/usr/lib/python2.6/site-packages/dnszonetest/cli.py", line 157, in main
    dnszonetest.compare()
  File "/usr/lib/python2.6/site-packages/dnszonetest/main.py", line 190, in compare
    self.get_zone_from_file()
  File "/usr/lib/python2.6/site-packages/dnszonetest/main.py", line 145, in get_zone_from_file
    'Unable to read zone file: {0}'.format(err)
dnszonetest.exceptions.NoZoneFileException: Unable to read zone file: [Errno 2] No such file or directory: 'zone.pizza '``

Can you make a nice error message for this issue?

**Comment by maartenq** [comment]
Of course. So you can you! :-)
Where is your pull request?
